language: node_js
cache:
  yarn: true
  directories:
  - node_modules
before_install:
  - npm install -g npm@5.5.1
notifications:
  email: false
node_js:
  - 8.6
os:
  - windows
  - osx
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
