language: node_js
notifications:
  email:
    on_success: change
    on_failure: always
node_js:
  - 6.10.3
cache:
  directories:
    - node_modules
before_script:
  - npm install -g gulp
before_install:
  - npm install -g npm@5.6.0
script:
  - source read.version.sh
  - echo "v$TRAVIS_TAG"
  - npm run minimize
after_success:
- npm run zipForGitReleases
before_deploy:
  - npm run minimize
deploy:
  - provider: npm
    email: ylakhdar@coveo.com
    skip_cleanup: true
    api_key:
      secure:  xtWYZnfn95kAOms1xu+CCGtYrlcD6sxHpann8dksQlZcqyIjgNUzh0swRNNEJ5OR3QYy5STCmM99MI6ubLKuGHz7x5ELm/XUIc4AkAgEWiSMQviuHIGpiiPwhFIOcCFoEOdozltK6zNPcyPTL3XcfuIV0yDFtxEDNUrVg2QdY238GbzRX1oaNWTlGRkGoi6geX0ifvO8pShHQdU9jDa3hIdXUwgw8sMFknsXOHpG278levKKx7YKOJzMvBPMMfhLJX4aVg3DJT8ezAOeUt6gpY18WNGYh+87guPcOdXXoTEwM6jMf8FnwZm5VAWP1Z3Ig/2dwavT4yJs9oio5Yj7/hgA5kRcS3x02W37iG/znXc59DH1M37iI4PA5rjTLYfCZUnby57ud8FkWEN4ZrM8A4E94A87JylBRTgxStAy2pTi2crIov9LWqRHyg0IJi+AKTtJn+jdkcwcO5qR8eu5x1NCkerRjXK4oWbwBHlgtX8/kW1prSaI9jmrY7oWAmKY7wsRCQC/bqaYfqw0oyriY+gpruCHA3sLF3CZ9D2uhtZqmuzbNMmu4BhanU/dmIW70bnSGixu5Ea6y2HDpImN8AIaKvWD8DtFqqTNLfoEjs2X1sa+uy7fDWs7GMk/5SBa2WkbrQfd7pYbqCxRrQgMcbxgK4N429bAEii8fkzlaKw=
    on:
      tags: true
      all_branches: true
  - provider: releases
    api_key:
      secure: xtWYZnfn95kAOms1xu+CCGtYrlcD6sxHpann8dksQlZcqyIjgNUzh0swRNNEJ5OR3QYy5STCmM99MI6ubLKuGHz7x5ELm/XUIc4AkAgEWiSMQviuHIGpiiPwhFIOcCFoEOdozltK6zNPcyPTL3XcfuIV0yDFtxEDNUrVg2QdY238GbzRX1oaNWTlGRkGoi6geX0ifvO8pShHQdU9jDa3hIdXUwgw8sMFknsXOHpG278levKKx7YKOJzMvBPMMfhLJX4aVg3DJT8ezAOeUt6gpY18WNGYh+87guPcOdXXoTEwM6jMf8FnwZm5VAWP1Z3Ig/2dwavT4yJs9oio5Yj7/hgA5kRcS3x02W37iG/znXc59DH1M37iI4PA5rjTLYfCZUnby57ud8FkWEN4ZrM8A4E94A87JylBRTgxStAy2pTi2crIov9LWqRHyg0IJi+AKTtJn+jdkcwcO5qR8eu5x1NCkerRjXK4oWbwBHlgtX8/kW1prSaI9jmrY7oWAmKY7wsRCQC/bqaYfqw0oyriY+gpruCHA3sLF3CZ9D2uhtZqmuzbNMmu4BhanU/dmIW70bnSGixu5Ea6y2HDpImN8AIaKvWD8DtFqqTNLfoEjs2X1sa+uy7fDWs7GMk/5SBa2WkbrQfd7pYbqCxRrQgMcbxgK4N429bAEii8fkzlaKw=
    file_glob: true
    file:
      - flow-sandbox.zip
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
# branches:
#   only:
#     - master
#     - develop
#     - /release\/[0-9]+\\.[0-9]+\\.[0-9]+/